# Site settings
title: Your Site Title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a brief description of your site. 
baseurl: "" # the subpath of your site, e.g., /blog
url: "" # the base hostname & protocol for your site, e.g., http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Optional settings
author: Your Name
twitter_username: your-handle
github_username:  your-handle

# Build settings
markdown: kramdown
permalink: pretty

